name: money-traning
static_sites:
- name: money-traning
  github:
    branch: main
    deploy_on_push: true
    repo: andresagudelo-financiera/money-traning
  build_command: npm run build
  output_dir: dist
